
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.9

# decorations = "Buttonless"

[font]

# normal.family = "FiraCodeNerdFontCompleteM-Retina"
normal.family = "FiraCode Nerd Font Mono"

[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]
# normal.family = "Hack Nerd Font Mono"

# size = 24
