theme = "enzo"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
mouse = true
scrolloff = 10

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-modification-indicator", "file-name"]
right = ["position", "total-line-numbers", "diagnostics", "file-type"]
separator = "|"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.lsp]
enable = true
display-inlay-hints = true

[keys.normal]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
