theme = "nightfox"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
mouse = false

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["position", "diagnostics", "file-encoding", "file-type"]
separator = "|"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[keys.normal]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
